[package]
name = "masterproef_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
tokio-tun = "0.7.0"
tokio-util = { version = "0.7.7", features = ["codec"] }
clap = { version = "4.1.8", features = ["derive"] }
rtnetlink = "0.12.0"
futures = "0.3.27"
toml = "0.7.3"
serde = { version = "1.0.158", features = ["derive"] }
rand = "0.8.5"
bytes = "1.4.0"
etherparse = "0.13.0"
x25519-dalek = "1.2.0"
