[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-cc"
ar = "aarch64-linux-musl-ar"
